# Introduction to Vectors and Matrices

In [7]:
import numpy as np
x = np.array([[1,0,4],[3,3,1]])
y = np.array([[2,5],[1,1],[3,2]])
x.dot(y)

array([[14, 13],
       [12, 20]])

In [8]:
x

array([[1, 0, 4],
       [3, 3, 1]])

In [9]:
y

array([[2, 5],
       [1, 1],
       [3, 2]])

# Basics of NumPy Array Object

In [10]:
# import numpy as np
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
print("We just create a ", type(x))

We just create a  <class 'numpy.ndarray'>


In [12]:
print("Our template has shape as" ,x.shape)

Our template has shape as (2, 3)


In [13]:
print("Total size is",x.size)

Total size is 6


In [14]:
print("The dimension of our array is " ,x.ndim)

The dimension of our array is  2


In [15]:
print("Data type of elements are",x.dtype)

Data type of elements are int32


In [16]:
print("It consumes",x.nbytes,"bytes")

It consumes 24 bytes


In [21]:
x = np.array([[1,2,3],[4,5,6]], dtype = float)
print(x)
print(x.nbytes)

[[1. 2. 3.]
 [4. 5. 6.]]
48


In [22]:
x = np.array([[1,2,3],[4,5,6]], dtype = complex)
print(x)
print(x.nbytes)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
96


In [26]:
x = np.array([[1,2,3],[4,-5,6]], dtype = np.int32)
print(x)
print(x.nbytes)

[[ 1  2  3]
 [ 4 -5  6]]
24


In [27]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.int64)
print("int64 comsues",x.nbytes, "bytes")
x = np.array([[1,2,3],[4,5,6]], dtype = np.int32)
print("int32 comsues",x.nbytes, "bytes")

int64 comsues 48 bytes
int32 comsues 24 bytes


In [29]:
x_copy = np.array(x, dtype = float)
x_copy 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
x_copy.dtype

dtype('float64')

In [34]:
x_copy_int = x_copy.astype(int)
x_copy_int

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
Data_Cancer = np.random.rand(100000,100)
print(type(Data_Cancer))
print(Data_Cancer.dtype)
print(Data_Cancer.nbytes)
Data_Cancer_New = np.array(Data_Cancer, dtype = np.float32)
print(Data_Cancer_New.nbytes)

# NumPy Array Operations

In [ ]:
my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
type(my_array)

In [ ]:
my_array +2

In [ ]:
my_array -1

In [ ]:
my_array *2

In [ ]:
my_array /2

In [ ]:
second_array = np.zeros(4) + 3
second_array 

In [ ]:
my_array - second_array 

In [ ]:
second_array / my_array 

In [ ]:
second_array = np.ones(4)+3
second_array

In [ ]:
my_array - second_array 

In [ ]:
second_array / my_array 

In [ ]:
second_array = np.identity(4)
second_array

In [ ]:
second_array = np.identity(4)+3
second_array

In [ ]:
my_array - second_array 

In [ ]:
second_array / my_array 

In [ ]:
x = np.arange(3,7,0.5)
x

In [ ]:
x = np.linspace(1.2, 40.5, num=20)
x

In [ ]:
np.geomspace(1, 625, num=5)

In [ ]:
np.logspace(3, 4, num=5)

In [ ]:
np.logspace(np.log10(3) , np.log10(4) , num=5)

In [ ]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x == y 

In [ ]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
np.array_equal(x,y)

In [ ]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x < y 

In [ ]:
x = np.array([0, 1, 0, 0], dtype=bool)
y = np.array([1, 1, 0, 1], dtype=bool)
np.logical_or(x,y)

In [ ]:
np.logical_and(x,y)

In [ ]:
x = np.array([12,16,57,11])
np.logical_or(x < 13, x > 50)

In [ ]:
x = np.array([1, 2, 3,4 ])
np.exp(x)

In [ ]:
np.log(x)

In [ ]:
np.sin(x)

In [ ]:
x = np.arange(9)
x

In [ ]:
x = np.arange(9).reshape((3, 3))
x

In [ ]:
x.T

In [ ]:
x = np.arange(6).reshape(2,3)
x

In [ ]:
x.T

In [ ]:
x = np.arange(9).reshape((3,3))
x

In [ ]:
np.sum(x)

In [ ]:
np.amin(x)

In [ ]:
np.amax(x)

In [ ]:
np.amin(x, axis=0)

In [ ]:
np.amin(x, axis=1)

In [ ]:
np.percentile(x, 80)

In [ ]:
x = np.array([1,-21,3,-3])
np.argmax(x)

In [ ]:
np.argmin(x)

In [ ]:
x = np.array([[2, 3, 5], [20, 12, 4]])
x

In [ ]:
np.mean(x)

In [ ]:
np.mean(x, axis=0)

In [ ]:
np.mean(x, axis=1)

In [ ]:
np.median(x)

In [ ]:
np.std(x)

# Working with Multidimensional Arrays

In [ ]:
c = np.ones((4, 4))
c*c

In [ ]:
c.dot(c)

In [ ]:
y = np.arange(15).reshape(3,5) 
x = np.arange(10).reshape(2,5)
new_array = np.vstack((y,x))
new_array

In [ ]:
y = np.arange(15).reshape(5,3) 
x = np.arange(10).reshape(5,2)
new_array = np.hstack((y,x))
new_array

In [ ]:
from scipy import stats
x= np.random.rand(100,10)
n, min_max, mean, var, skew, kurt = stats.describe(x)
new_array = np.vstack((mean,var,skew,kurt,min_max[0],min_max[1]))
new_array.T

In [ ]:
import numpy.ma as ma
x = np.arange(6)
print(x.mean())
masked_array = ma.masked_array(x, mask=[1,0,0,0,0,0])
masked_array.mean()

In [ ]:
x = np.arange(25, dtype = float).reshape(5,5)
x[x<5] = np.nan
x

In [ ]:
np.where(np.isnan(x), ma.array(x, mask=np.isnan(x)).mean(axis=0), x)

# Indexing, Slicing, Reshaping, Resizing, Broadcasting

In [ ]:
x = ["USA","France", "Germany","England"]
x[2]

In [ ]:
x = ('USA',3,"France",4)
x[2]

In [ ]:
x = np.arange(10)
x

In [ ]:
x[5]

In [ ]:
x[-2]

In [ ]:
x[2:8]

In [ ]:
x[:]

In [ ]:
x[2:8:2]

In [ ]:
x = np.reshape(np.arange(16),(4,4))
x

In [ ]:
x[1:3]

In [ ]:
x[:,1:3]

In [ ]:
x[1:3,1:3]

In [ ]:
x = np.reshape(np.arange(16),(4,4))
x

In [ ]:
x[[0,1,2],[0,1,3]]

In [ ]:
x = np.arange(16).reshape(4,4)
x

In [ ]:
np.resize(x,(2,2))

In [ ]:
np.resize(x,(6,6))

In [ ]:
x = np.arange(16).reshape(4,4)
y = np.arange(6).reshape(2,3)
x+y

In [ ]:
x = np.ones(16).reshape(4,4)
y = np.arange(4)
x*y

In [ ]:
x = np.arange(4).reshape(2,2)
x

In [ ]:
y = np.arange(2).reshape(1,2)
y

In [ ]:
x*y